import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import React from "react";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
  title: "Betandro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-black">
        <Providers>
          <Header />
          <main className="flex-grow max-w-screen-xl mx-auto px-4 py-6 mt-[56px] mb-[56px]">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
